FROM python:3.8-slim-buster

WORKDIR app/
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

ENTRYPOINT [ "python3", "calc_hamming_dist.py" ]

# Build with: docker build -t get_dist .
# Run with: docker run --rm --mount type=bind,source="$(pwd)",target=/app get_dist -n 1 --simulate tiny_alignment.fasta