# Global args persist across stages
ARG HARVEST_VER="1.3"

FROM ubuntu:xenial as builder
ARG HARVEST_VER

ENV LD_LIBRARY_PATH="/usr/lib:/usr/local/lib"

# Update package index
RUN apt-get update && apt-get upgrade

RUN apt-get install -y \
    automake-1.15 \
    build-essential \
    wget \
    protobuf-compiler \
    libprotobuf-dev \
    capnproto \
    libcapnp-dev \
    zlib1g-dev

# Move some static libraries HarvestTools demands to where it wants to see them
RUN cp /usr/lib/x86_64-linux-gnu/libprotobuf.a /usr/lib/
RUN cp /usr/lib/x86_64-linux-gnu/libcapnp.a /usr/lib/
RUN cp /usr/lib/x86_64-linux-gnu/libkj.a /usr/lib/

# Install HarvestTools
RUN wget https://github.com/marbl/harvest-tools/archive/refs/tags/v$HARVEST_VER.tar.gz
RUN tar xvf v$HARVEST_VER.tar.gz
WORKDIR harvest-tools-$HARVEST_VER
RUN ./bootstrap.sh
RUN ./configure --with-protobuf=/usr --with-capnp=/usr --prefix=/usr/local && make && make install

# Build with: docker build -t harvest-tools -f Dockerfile-from-source .
# Run with: docker run --rm harvest-tools harvesttools --version