# This workflow builds a Singularity image based on a Docker image

name: Build Singularity image

on: workflow_dispatch
#on:
#  workflow_call:
#    inputs:
#      dockerhub_image:
#        required: true
#        type: string

jobs:

  build_singularity:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out Repo
        uses: actions/checkout@v2

      - name: Set up Singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3

      - name: Run a singularity container
#        run: singularity run docker://${{ inputs.dockerhub_image }} pwd
        run: singularity run docker://snads/harvesttools-1.3 harvesttools --version
