# This caller workflow tests, builds, and pushes the image to Docker Hub.

name: Build & push ClonalFrameML image

on: workflow_dispatch

jobs:

  test:
    uses: SarahNadeau/bioinf-containers/.github/workflows/build-to-test.yml@master
    with:
      path_to_context: "./clonalframeml/1.12"  # where the build context is
      cache: "clonalframeml" # a unique name here specifies a unique cache of Docker layers (to avoid filling up a single cache with unrelated layers from different images)

  build-and-push:
    needs: test  # this jobs needs to run serially, after testing succeeds
    uses: SarahNadeau/bioinf-containers/.github/workflows/build-and-push.yml@master
    with:
      path_to_context: "./clonalframeml/1.12"
      cache: "clonalframeml"
      container_name: "clonalframeml"  # name of the container for Docker Hub
      tag: 1.12
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  run-singularity:
    needs: build-and-push  # test singularity run on newly pushed Docker image
    uses: SarahNadeau/bioinf-containers/.github/workflows/run-singularity.yml@master
    with:
      dockerhub_image: "snads/clonalframeml:1.12"
      command: "ClonalFrameML -version"
