# This caller workflow builds and pushes the image to Docker Hub.
# It also tests that a Singularity container can be run from the Docker image.

name: Build & push Hamming Distance image

on: workflow_dispatch

jobs:

  build-and-push:
    uses: SarahNadeau/bioinf-containers/.github/workflows/build-and-push.yml@master
    with:
      path_to_context: "./hamming_dist/python_implementation"
      dockerfile_name: "Dockerfile"
      cache: "hamming-dist"
      container_name: "hamming-dist"
      tag: "1.0"
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  run-singularity:
    needs: build-and-push  # test singularity run on newly pushed Docker image
    uses: SarahNadeau/bioinf-containers/.github/workflows/run-singularity.yml@master
    with:
      dockerhub_image: "snads/hamming-dist:1.0"
