# This is a basic workflow to built-to-test and then build-and-push that is manually triggered

name: Build, test & push HarvestTools 1.3 image

# Run workflow when manually triggered using the UI.
on: workflow_dispatch

jobs:

  test_build_push:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    # See https://docs.docker.com/engine/reference/commandline/buildx_build/
    # And https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-harvesttools-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-harvesttools-buildx

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build to test
      id: docker_build_to_test
      uses: docker/build-push-action@v2
      with:
        context: ./harvesttools
        file: ./harvesttools/Dockerfile-from-source
        target: test
        push: false
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./harvesttools
        file: ./harvesttools/Dockerfile-from-source
        push: true
        target: app
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/harvesttools-1.3:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
