# This is a basic workflow to built-to-test and then build-and-push that is manually triggered

name: HarvestTools Manual workflow

# Run workflow when manually triggered using the UI.
on: workflow_dispatch

jobs:

  test_build_push:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v2

    - name: Build to test
      run: docker build --target test -f harvesttools/Dockerfile-from-source harvesttools/
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./harvesttools
        file: ./harvesttools/Dockerfile_from_source
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/harvesttools:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
