# This caller workflow tests, builds, and pushes the image to Docker Hub.
# It also tests that a Singularity container can be run from the Docker image.

name: Build & push ParSNP image

on: workflow_dispatch

jobs:

  test:
    uses: SarahNadeau/bioinf-containers/.github/workflows/build-to-test.yml@master
    with:
      path_to_context: "./parsnp/1.5.6"
      dockerfile_name: "Dockerfile"
      cache: "parsnp"

  build-and-push:
    needs: test  # this jobs needs to run serially, after testing succeeds
    uses: SarahNadeau/bioinf-containers/.github/workflows/build-and-push.yml@master
    with:
      path_to_context: "./parsnp/1.5.6"
      dockerfile_name: "Dockerfile"
      cache: "parsnp"
      container_name: "parsnp"
      tag: 1.5.6
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  run-singularity:
    needs: build-and-push  # test singularity run on newly pushed Docker image
    uses: SarahNadeau/bioinf-containers/.github/workflows/run-singularity.yml@master
    with:
      dockerhub_image: "snads/parsnp:1.5.6"
